In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/fake_news.csv")
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df.shape

(20800, 5)

In [ ]:
df["title"][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [ ]:
df["text"][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It By Darrell Lucus on October 30, 2016 Subscribe Jason Chaffetz on the stump in American Fork, Utah ( image courtesy Michael Jolley, available under a Creative Commons-BY license) \nWith apologies to Keith Olbermann, there is no doubt who the Worst Person in The World is this week–FBI Director James Comey. But according to a House Democratic aide, it looks like we also know who the second-worst person is as well. It turns out that when Comey sent his now-infamous letter announcing that the FBI was looking into emails that may be related to Hillary Clinton’s email server, the ranking Democrats on the relevant committees didn’t hear about it from Comey. They found out via a tweet from one of the Republican committee chairmen. \nAs we now know, Comey notified the Republican chairmen and Democratic ranking members of the House Intelligence, Judiciary, and Oversight committees that his agency was reviewing emai

In [ ]:
# Drop NaN values
df = df.dropna()

In [ ]:
# Get the Independent Features
X=df.drop('label',axis=1)

In [ ]:
# Get the Dependent features
y=df['label']

In [ ]:
X.shape

(18285, 4)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.12.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size=5000

#Onehot Representation

In [ ]:
messages=X.copy()

In [ ]:
messages.reset_index(inplace=True)

# I used reset_index because I had dropped NaN values from the X.

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

# In one hot representation, we basically require the index of words based on the vocabulary size.

[[2562, 1838, 623, 1052, 3153, 4201, 4315, 4414, 4107, 1566],
 [3884, 923, 3837, 4449, 2782, 4389, 1793],
 [1793, 4404, 4228, 2736],
 [1978, 2015, 1671, 4761, 352, 4532],
 [1676, 2782, 3598, 3017, 4759, 53, 2782, 1380, 3455, 2882],
 [503,
  1947,
  3790,
  1234,
  3347,
  1948,
  3672,
  1161,
  3561,
  4132,
  3508,
  4130,
  3081,
  2045,
  1793],
 [890, 3541, 3003, 3519, 1589, 1983, 1556, 4957, 4774, 1727, 2842],
 [3789, 3291, 3045, 1733, 1250, 2328, 1948, 921, 4774, 1727, 2842],
 [1507, 1153, 1581, 4046, 1409, 1273, 1181, 4358, 1948, 4110],
 [3105, 4584, 4347, 494, 1051, 3380, 4114, 2662],
 [2885, 305, 1007, 4416, 3615, 2705, 592, 1005, 4079, 3131, 4297],
 [4761, 1878, 3153, 1273, 1948, 1250],
 [2683, 4810, 4735, 1720, 3109, 458, 2313, 3845, 1303],
 [225, 2982, 372, 3492, 4099, 1266, 4862, 4774, 1727, 2842],
 [1900, 2723, 2385, 4206, 3939, 4774, 1727, 2842],
 [428, 1671, 1658, 2267, 2533, 3223, 2314, 2269, 4523, 2082],
 [4532, 1513, 923],
 [473, 2445, 4118, 661, 1948, 2335, 2475, 1

#Embedding Representation

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

# If length of the sentences are different then we use "pad_sequences" to make all sentences of equal length. First we have fixed the length of the sentence. If we are using the padding parameter as "pre" then it will add 0 in the begining and if we use "post" then it wil add 0 in the end to make the sentences of equal length.

[[   0    0    0 ... 4414 4107 1566]
 [   0    0    0 ... 2782 4389 1793]
 [   0    0    0 ... 4404 4228 2736]
 ...
 [   0    0    0 ... 4774 1727 2842]
 [   0    0    0 ... 4892 1067 3785]
 [   0    0    0 ... 4976 1929 3888]]


In [ ]:
#This is what we require as input to give our embedding layer.

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2562,
       1838,  623, 1052, 3153, 4201, 4315, 4414, 4107, 1566], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
# In embedding layer, it takes the input and converts it into specific number of features or vectors. Based on that number of features it give the output.
# Here I have taken it as 40, even we can take 100 features too.
# Then first I have created a sequencial layer.
# In the second layer, I am adding an embedding layer. Then I will pass the output of this embedding layer to LSTM layer. Here I have taken one LSTM layer with 100 neurons.
# Then I have added a dense layer, because it is a classification problem.

In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

#Model Training

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 23s 81ms/step - loss: 0.3324 - accuracy: 0.8506 - val_loss: 0.2125 - val_accuracy: 0.9089
Epoch 2/10
192/192 [==============================] - 4s 19ms/step - loss: 0.1436 - accuracy: 0.9456 - val_loss: 0.2171 - val_accuracy: 0.9057
Epoch 3/10
192/192 [==============================] - 3s 15ms/step - loss: 0.1043 - accuracy: 0.9620 - val_loss: 0.2246 - val_accuracy: 0.9132
Epoch 4/10
192/192 [==============================] - 3s 13ms/step - loss: 0.0777 - accuracy: 0.9736 - val_loss: 0.2763 - val_accuracy: 0.9072
Epoch 5/10
192/192 [==============================] - 2s 10ms/step - loss: 0.0526 - accuracy: 0.9832 - val_loss: 0.3162 - val_accuracy: 0.9072
Epoch 6/10
192/192 [==============================] - 2s 11ms/step - loss: 0.0350 - accuracy: 0.9896 - val_loss: 0.3468 - val_accuracy: 0.9128
Epoch 7/10
192/192 [==============================] - 2s 11ms/step - loss: 0.0244 - accuracy: 0.9931 - val_loss: 0.4367 - val_accuracy: 0.910

#Performance Metrics And Accuracy

#Adding Dropout

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
# Above adding dropout layer is just like a hyperparameter tuning.

In [ ]:
# Now again perform performance metrics and accuracy.